### ISSUE TITLE
Requesting CyberChef for Splunk certified for Splunk Cloud

### ISSUE THREAD

**Issue by tevans1957** [NDietrich/CyberChef-for-Splunk#11] opened 2021-12-17 21:07 UTC
Hi Noah,

We have interest having CyberChef for Splunk certified for Splunk Cloud. During the vetting process a few questions were identified and we wanted to reach out to you. Not sure if you are interested in having the app vetting for Splunk Cloud but if you are could please provide any feedback to questions below.

The app appears to have a sym link and over 100MB of node modules. Please ask developer if this is appropriate. Also, ask if they can rebuild with ./splunk package app <appName> command as that often resolves issues.

AppInspect does not seem to work with this app. Developer should run AppInspect API on the app before submitting to Splunkbase and can work with devinfo@splunk.com if issues with packaging persist.

Best regards,

Thomas Evans
Splunk

**Comment by NDietrich** [comment] 2022-01-05 12:22
Dupe of #10 .  
also v1.1.1 submitted to splunkbase for AppInspect approval

**Closed by NDietrich** 2022-01-05 12:22 UTC
Labels: duplicate
